Add MysqlGTIDSet.Add() and Minus() methods
go-mysql-org/go-mysql pull request #662
Opened 2022-01-10 20:43 UTC by ostinru

Add MysqlGTIDSet.Add() and Minus() methods, so it will help users to estimate GTID sets that are stored in binlog file.

2022-01-11 08:08 UTC, atercattus requested changes
lgtm. But fix the tests and lint, please.

2022-01-11 08:08 UTC, atercattus commented on mysql/mysql_gtid.go
> +	s.Intervals = s.Intervals.Normalize()
`s.Intervals = n.Intervals.Normalize()`?

2022-01-11 13:19 UTC, atercattus approved these changes

2022-01-11 14:35 UTC, ostinru commented
@atercattus, could you please trigger github workflow checks for this PR?
I have no permissions for doing this.

2022-01-11 16:12 UTC, atercattus commented
Sorry, I forgot about this 🙂

2022-01-12 10:15 UTC, ostinru commented
Hi, @atercattus it seems that this PR is ready to be merged. Could you please merge it?

2022-01-12 10:21 UTC, merged